
spring:
  main:
    web-application-type: none
  datasource:
    url: jdbc:h2:file:./data/pmDB;
    driver-class-name: org.h2.Driver # The JBDC Driver for H2
    username: sa
    password:

  h2:
    console:
      enabled: true
    path: /h2-console

  jpa :
    hibernate:
      ddl-auto: update # Automatically set or update the Db tables based on the entities
    show-sql:  true # Enables the use of Query by the JPA methods